require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe User2sController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # User2. As you add validations to User2, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # User2sController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user2s as @user2s" do
      user2 = User2.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:user2s)).to eq([user2])
    end
  end

  describe "GET show" do
    it "assigns the requested user2 as @user2" do
      user2 = User2.create! valid_attributes
      get :show, {:id => user2.to_param}, valid_session
      expect(assigns(:user2)).to eq(user2)
    end
  end

  describe "GET new" do
    it "assigns a new user2 as @user2" do
      get :new, {}, valid_session
      expect(assigns(:user2)).to be_a_new(User2)
    end
  end

  describe "GET edit" do
    it "assigns the requested user2 as @user2" do
      user2 = User2.create! valid_attributes
      get :edit, {:id => user2.to_param}, valid_session
      expect(assigns(:user2)).to eq(user2)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User2" do
        expect {
          post :create, {:user2 => valid_attributes}, valid_session
        }.to change(User2, :count).by(1)
      end

      it "assigns a newly created user2 as @user2" do
        post :create, {:user2 => valid_attributes}, valid_session
        expect(assigns(:user2)).to be_a(User2)
        expect(assigns(:user2)).to be_persisted
      end

      it "redirects to the created user2" do
        post :create, {:user2 => valid_attributes}, valid_session
        expect(response).to redirect_to(User2.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user2 as @user2" do
        post :create, {:user2 => invalid_attributes}, valid_session
        expect(assigns(:user2)).to be_a_new(User2)
      end

      it "re-renders the 'new' template" do
        post :create, {:user2 => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user2" do
        user2 = User2.create! valid_attributes
        put :update, {:id => user2.to_param, :user2 => new_attributes}, valid_session
        user2.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested user2 as @user2" do
        user2 = User2.create! valid_attributes
        put :update, {:id => user2.to_param, :user2 => valid_attributes}, valid_session
        expect(assigns(:user2)).to eq(user2)
      end

      it "redirects to the user2" do
        user2 = User2.create! valid_attributes
        put :update, {:id => user2.to_param, :user2 => valid_attributes}, valid_session
        expect(response).to redirect_to(user2)
      end
    end

    describe "with invalid params" do
      it "assigns the user2 as @user2" do
        user2 = User2.create! valid_attributes
        put :update, {:id => user2.to_param, :user2 => invalid_attributes}, valid_session
        expect(assigns(:user2)).to eq(user2)
      end

      it "re-renders the 'edit' template" do
        user2 = User2.create! valid_attributes
        put :update, {:id => user2.to_param, :user2 => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user2" do
      user2 = User2.create! valid_attributes
      expect {
        delete :destroy, {:id => user2.to_param}, valid_session
      }.to change(User2, :count).by(-1)
    end

    it "redirects to the user2s list" do
      user2 = User2.create! valid_attributes
      delete :destroy, {:id => user2.to_param}, valid_session
      expect(response).to redirect_to(user2s_url)
    end
  end

end
